framework: jest
postMerge:
  pattern:
    - "./test/index.test.ts"
preMerge:
  pattern:
    - "./test/index.test.ts"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 1.0
